language: csharp
solution: todo-manager.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore todo-manager.sln
script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  - grep "Test Results" build.log

  mono:
  - latest