language: csharp
sudo: required
dist: trusty

mono: latest
dotnet: 2.1.4

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_install:
  - npm install bower -g

script:
  - ./build.sh
